[package]
authors.workspace    = true
categories.workspace = true
description          = "Biome implementing for matching Grit Patterns"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "biome_grit_patterns"
publish              = false
repository.workspace = true
version              = "0.0.1"

[dependencies]
anyhow               = "1.0.52"
biome_console        = { workspace = true }
biome_diagnostics    = { workspace = true }
biome_grit_parser    = { workspace = true }
biome_grit_syntax    = { workspace = true }
biome_rowan          = { workspace = true }
grit-pattern-matcher = { git = "https://github.com/arendjr/gritql.git", branch = "trimmed-submodules" }
grit-util            = { git = "https://github.com/arendjr/gritql.git", branch = "trimmed-submodules" }
im                   = { version = "15.1.0" }
serde                = { workspace = true, features = ["derive"] }

[lints]
workspace = true
